### ISSUE TITLE
Ember > 2.0 deprecation warning

### ISSUE THREAD

**Issue by acwright** [kennethdavidbuck/ember-cli-storagekit#2]
DEPRECATION: The `initialize` method for Application initializer 'inject-storagekit' should take only one argument - `App`, an instance of an `Application`. [deprecation id: ember-application.app-initializer-initialize-arguments] See http://emberjs.com/deprecations/v2.x/#toc_initializer-arity for more details.

**Comment by kennethdavidbuck** [comment]
Thanks @acwright! This issue should be resolved as part of a744780e47c3e90e0a878f734dabaef99ed545d0, and will released in v0.3.2.

**Comment by kennethdavidbuck** [comment]
Ok, I just published v0.3.2, please let me know if you have any other issues after updating.
