### ISSUE TITLE
getItems method

### ISSUE THREAD

**Issue by pasikonik** [kennethdavidbuck/ember-cli-storagekit#5]
Did you consider `getItems` method?

I think it would be helpful method sometimes.

e.g.

`const { keyOne, keyTwo, keyThree } = this.get('localStorage').getItems('keyOne, keyTwo, keyThree`?

and also similarly `setItems` method

**Comment by kennethdavidbuck** [comment]
@Pasikonik two of the the original goals I had when writing this addon were to keep it simple, and to stay true to the existing storage apis that developers are already familiar with. That being said, I could see how #getItems and #setItems could serve as useful analogs to Ember's #getProperties and #setProperties (I imagine the signatures should match as well). It might even be worthwhile to add a #removeItems method as well. Is it something that you would be interested in submitting a PR for?

**Comment by kennethdavidbuck** [comment]
Closing this for now, but can reopened if there is ever any renewed interest.
